<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeederMexicano extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $style = 'Mexicano';
        $products = [
            // PISOS INTERIORES
            [
                'category_name' => 'PISOS INTERIORES',
                'style' => $style,
                'pre_code' => 'PIN01',
                'variant_code' => 'X01',
                'version' => '00',
                'title' => 'MARMOL BLANCO ARENA PULIDO MATE. FORMATO 30 cm X LARGOS LIBRES',
                'brand' => 'MIDO',
                'base_price' => 544.00,
                'image_url' => '',
            ],
            [
                'category_name' => 'PISOS INTERIORES',
                'style' => $style,
                'pre_code' => 'PIN01',
                'variant_code' => 'X02',
                'version' => '00',
                'title' => 'MARMOL SANTO TOMÁS PULIDO MATE. FORMATO 30 cm x LARGOS LIBRES',
                'brand' => 'MIDO',
                'base_price' => 530.00,
                'image_url' => '',
            ],
            [
                'category_name' => 'PISOS INTERIORES',
                'style' => $style,
                'pre_code' => 'PIN01',
                'variant_code' => 'X03',
                'version' => '00',
                'title' => 'CERÁMICO TIPO PIEDRA MOD. SANTA MÓNICA COLOR PIÑON. FORMATO 40X40',
                'brand' => 'INTERCERAMIC',
                'base_price' => 195.00,
                'image_url' => '',
            ],
            [
                'category_name' => 'PISOS INTERIORES',
                'style' => $style,
                'pre_code' => 'PIN01',
                'variant_code' => 'X04',
                'version' => '00',
                'title' => 'CERÁMICO TIPO PIEDRA MOD. SANTA MÓNICA COLOR GRAFITO. FORMATO 40X40',
                'brand' => 'INTERCERAMIC',
                'base_price' => 195.00,
                'image_url' => '',
            ],
            [
                'category_name' => 'PISOS INTERIORES',
                'style' => $style,
                'pre_code' => 'PIN01',
                'variant_code' => 'X05',
                'version' => '00',
                'title' => 'CERÁMICO TIPO CEMENTO MODELO CREATO COLOR TAUPE. FORMATO 60X120',
                'brand' => 'INTERCERAMIC',
                'base_price' => 359.00,
                'image_url' => '',
            ],
            [
                'category_name' => 'PISOS INTERIORES',
                'style' => $style,
                'pre_code' => 'PIN01',
                'variant_code' => 'X06',
                'version' => '00',
                'title' => 'CERÁMICO TIPO CEMENTO MODELO CREATO COLOR TERRACOTA. FORMATO 60X120',
                'brand' => 'INTERCERAMIC',
                'base_price' => 359.00,
                'image_url' => '',
            ],
            // PISOS REGADERAS
            [
                'category_name' => 'PISOS REGADERAS',
                'style' => $style,
                'pre_code' => 'PRE01',
                'variant_code' => 'X01',
                'version' => '00',
                'title' => 'MARMOL BLANCO ARENA AVEJENTADO MATE. FORMATO 30 cm X LARGOS LIBRES',
                'brand' => 'MIDO',
                'base_price' => 439.00,
                'image_url' => '',
            ],
            [
                'category_name' => 'PISOS REGADERAS',
                'style' => $style,
                'pre_code' => 'PRE01',
                'variant_code' => 'X02',
                'version' => '00',
                'title' => 'MARMOL SANTO TOMÁS PULIDO AVEJENTADO. FORMATO 30 cm x LARGOS LIBRES',
                'brand' => 'MIDO',
                'base_price' => 544.00,
                'image_url' => '',
            ],
            [
                'category_name' => 'PISOS REGADERAS',
                'style' => $style,
                'pre_code' => 'PRE01',
                'variant_code' => 'X03',
                'version' => '00',
                'title' => 'CERÁMICO TIPO PIEDRA MOD. MATERIA COLOR TAUPE. FORMATO 60X60',
                'brand' => 'INTERCERAMIC',
                'base_price' => 289.00,
                'image_url' => '',
            ],
            [
                'category_name' => 'PISOS REGADERAS',
                'style' => $style,
                'pre_code' => 'PRE01',
                'variant_code' => 'X04',
                'version' => '00',
                'title' => 'CERÁMICO TIPO PIEDRA MOD. MATERIA COLOR MARRONE. FORMATO 60X60',
                'brand' => 'INTERCERAMIC',
                'base_price' => 289.00,
                'image_url' => '',
            ],
            [
                'category_name' => 'PISOS REGADERAS',
                'style' => $style,
                'pre_code' => 'PRE01',
                'variant_code' => 'X05',
                'version' => '00',
                'title' => 'CERÁMICO TIPO PIEDRA MOD. SANTA MÓNICA COLOR PIÑON. FORMATO 40X40',
                'brand' => 'INTERCERAMIC',
                'base_price' => 195.00,
                'image_url' => '',
            ],
            [
                'category_name' => 'PISOS REGADERAS',
                'style' => $style,
                'pre_code' => 'PRE01',
                'variant_code' => 'X06',
                'version' => '00',
                'title' => 'CERÁMICO TIPO PIEDRA MOD. SANTA MÓNICA COLOR GRAFITO. FORMATO 40X40',
                'brand' => 'INTERCERAMIC',
                'base_price' => 195.00,
                'image_url' => '',
            ],
            // MESETA COCINA
            [
                'category_name' => 'MESETA COCINA',
                'style' => $style,
                'pre_code' => 'MES01',
                'variant_code' => 'X01',
                'version' => '00',
                'title' => 'GRANITO ITAUNAS PULIDO',
                'brand' => 'MIDO',
                'base_price' => 80.00, // USD
                'image_url' => '',
            ],
            [
                'category_name' => 'MESETA COCINA',
                'style' => $style,
                'pre_code' => 'MES01',
                'variant_code' => 'X02',
                'version' => '00',
                'title' => 'GRANITO SAN GABRIEL LEATHER',
                'brand' => 'MIDO',
                'base_price' => 95.00, // USD
                'image_url' => '',
            ],
            [
                'category_name' => 'MESETA COCINA',
                'style' => $style,
                'pre_code' => 'MES01',
                'variant_code' => 'X03',
                'version' => '00',
                'title' => 'GRANITO WHITE ROMANO',
                'brand' => 'MIDO',
                'base_price' => 100.00, // USD
                'image_url' => '',
            ],
            // MESETAS BAÑOS
            [
                'category_name' => 'MESETAS BAÑOS',
                'style' => $style,
                'pre_code' => 'MES02',
                'variant_code' => 'X01',
                'version' => '00',
                'title' => 'GRANITO ITAUNAS PULIDO',
                'brand' => 'MIDO',
                'base_price' => 80.00, // USD
                'image_url' => '',
            ],
            [
                'category_name' => 'MESETAS BAÑOS',
                'style' => $style,
                'pre_code' => 'MES02',
                'variant_code' => 'X02',
                'version' => '00',
                'title' => 'GRANITO SAN GABRIEL LEATHER',
                'brand' => 'MIDO',
                'base_price' => 95.00, // USD
                'image_url' => '',
            ],
            [
                'category_name' => 'MESETAS BAÑOS',
                'style' => $style,
                'pre_code' => 'MES02',
                'variant_code' => 'X03',
                'version' => '00',
                'title' => 'GRANITO WHITE ROMANO',
                'brand' => 'MIDO',
                'base_price' => 100.00, // USD
                'image_url' => '',
            ],
            // MUROS REGADERAS
            [
                'category_name' => 'MUROS REGADERAS',
                'style' => $style,
                'pre_code' => 'MRE01',
                'variant_code' => 'X01',
                'version' => '00',
                'title' => 'MARMOL BLANCO ARENA PULIDO MATE. FORMATO 30 cm X LARGOS LIBRES',
                'brand' => 'MIDO',
                'base_price' => 544.00,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS REGADERAS',
                'style' => $style,
                'pre_code' => 'MRE01',
                'variant_code' => 'X02',
                'version' => '00',
                'title' => 'MARMOL SANTO TOMÁS PULIDO MATE. FORMATO 30 cm x LARGOS LIBRES',
                'brand' => 'MIDO',
                'base_price' => 544.00,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS REGADERAS',
                'style' => $style,
                'pre_code' => 'MRE01',
                'variant_code' => 'X03',
                'version' => '00',
                'title' => 'CERÁMICO TIPO PIEDRA MOD. MATERIA COLOR TAUPE. FORMATO 60X60',
                'brand' => 'INTERCERAMIC',
                'base_price' => 289.00,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS REGADERAS',
                'style' => $style,
                'pre_code' => 'MRE01',
                'variant_code' => 'X04',
                'version' => '00',
                'title' => 'CERÁMICO TIPO PIEDRA MOD. MATERIA COLOR MARRONE. FORMATO 60X60',
                'brand' => 'INTERCERAMIC',
                'base_price' => 289.00,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS REGADERAS',
                'style' => $style,
                'pre_code' => 'MRE01',
                'variant_code' => 'X05',
                'version' => '00',
                'title' => 'CERÁMICO TIPO PIEDRA MOD. SANTA MÓNICA COLOR PIÑON. FORMATO 40X40',
                'brand' => 'INTERCERAMIC',
                'base_price' => 195.00,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS REGADERAS',
                'style' => $style,
                'pre_code' => 'MRE01',
                'variant_code' => 'X06',
                'version' => '00',
                'title' => 'CERÁMICO TIPO PIEDRA MOD. SANTA MÓNICA COLOR GRAFITO. FORMATO 40X40',
                'brand' => 'INTERCERAMIC',
                'base_price' => 195.00,
                'image_url' => '',
            ],
            // MUROS INTERIORES BASE
            [
                'category_name' => 'MUROS INTERIORES BASE',
                'style' => $style,
                'pre_code' => 'MIB01',
                'variant_code' => 'X01',
                'version' => '00',
                'title' => 'PINTURA BLANCO CLARA 020-01',
                'brand' => 'COMEX',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS INTERIORES BASE',
                'style' => $style,
                'pre_code' => 'MIB01',
                'variant_code' => 'X02',
                'version' => '00',
                'title' => 'PLASTER CONCRETO APARENTE',
                'brand' => 'KIMIKOLOR',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS INTERIORES BASE',
                'style' => $style,
                'pre_code' => 'MIB01',
                'variant_code' => 'X03',
                'version' => '00',
                'title' => 'PLASTER BLANCO SASCAB',
                'brand' => 'KIMIKOLOR',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS INTERIORES BASE',
                'style' => $style,
                'pre_code' => 'MIB01',
                'variant_code' => 'X04',
                'version' => '00',
                'title' => 'PINTURA GRIS ESPÁTULA 312-02',
                'brand' => 'COMEX',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS INTERIORES BASE',
                'style' => $style,
                'pre_code' => 'MIB01',
                'variant_code' => 'X05',
                'version' => '00',
                'title' => 'PINTURA NEUTRO MUSEO 276-01',
                'brand' => 'COMEX',
                'base_price' => 0,
                'image_url' => '',
            ],
            // MUROS INTERIORES ACENTO
            [
                'category_name' => 'MUROS INTERIORES ACENTO',
                'style' => $style,
                'pre_code' => 'MIA01',
                'variant_code' => 'X01',
                'version' => '00',
                'title' => 'PINTURA BLANCO CLARA 020-01',
                'brand' => 'COMEX',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS INTERIORES ACENTO',
                'style' => $style,
                'pre_code' => 'MIA01',
                'variant_code' => 'X02',
                'version' => '00',
                'title' => 'PLASTER CONCRETO APARENTE',
                'brand' => 'KIMIKOLOR',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS INTERIORES ACENTO',
                'style' => $style,
                'pre_code' => 'MIA01',
                'variant_code' => 'X03',
                'version' => '00',
                'title' => 'PLASTER BLANCO SASCAB',
                'brand' => 'KIMIKOLOR',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS INTERIORES ACENTO',
                'style' => $style,
                'pre_code' => 'MIA01',
                'variant_code' => 'X04',
                'version' => '00',
                'title' => 'PLASTER ROSA',
                'brand' => 'KIMIKOLOR',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS INTERIORES ACENTO',
                'style' => $style,
                'pre_code' => 'MIA01',
                'variant_code' => 'X05',
                'version' => '00',
                'title' => 'PLASTER AZUL',
                'brand' => 'KIMIKOLOR',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS INTERIORES ACENTO',
                'style' => $style,
                'pre_code' => 'MIA01',
                'variant_code' => 'X06',
                'version' => '00',
                'title' => 'PLASTER NARANJA TICUL',
                'brand' => 'KIMIKOLOR',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS INTERIORES ACENTO',
                'style' => $style,
                'pre_code' => 'MIA01',
                'variant_code' => 'X07',
                'version' => '00',
                'title' => 'PLASTER ROJO CONKAL',
                'brand' => 'KIMIKOLOR',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS INTERIORES ACENTO',
                'style' => $style,
                'pre_code' => 'MIA01',
                'variant_code' => 'X08',
                'version' => '00',
                'title' => 'PINTURA GRIS ESPÁTULA 312-02',
                'brand' => 'COMEX',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS INTERIORES ACENTO',
                'style' => $style,
                'pre_code' => 'MIA01',
                'variant_code' => 'X09',
                'version' => '00',
                'title' => 'PINTURA NEUTRO MUSEO 276-01',
                'brand' => 'COMEX',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS INTERIORES ACENTO',
                'style' => $style,
                'pre_code' => 'MIA01',
                'variant_code' => 'X10',
                'version' => '00',
                'title' => 'PINTURA ROJO AJIJIC 083-03',
                'brand' => 'COMEX',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS INTERIORES ACENTO',
                'style' => $style,
                'pre_code' => 'MIA01',
                'variant_code' => 'X11',
                'version' => '00',
                'title' => 'PINTURA AZUL SURF 176-03',
                'brand' => 'COMEX',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS INTERIORES ACENTO',
                'style' => $style,
                'pre_code' => 'MIA01',
                'variant_code' => 'X12',
                'version' => '00',
                'title' => 'PINTURA NARANJA INCIENSO H3-09',
                'brand' => 'COMEX',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS INTERIORES ACENTO',
                'style' => $style,
                'pre_code' => 'MIA01',
                'variant_code' => 'X13',
                'version' => '00',
                'title' => 'PINTURA MORADO ANTICA A4-08',
                'brand' => 'COMEX',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS INTERIORES ACENTO',
                'style' => $style,
                'pre_code' => 'MIA01',
                'variant_code' => 'X14',
                'version' => '00',
                'title' => 'PINTURA ROJO AMAPOLA D2-14',
                'brand' => 'COMEX',
                'base_price' => 0,
                'image_url' => '',
            ],

            // MUROS EXTERIOR BASE
            [
                'category_name' => 'MUROS EXTERIOR BASE',
                'style' => $style,
                'pre_code' => 'MEB01',
                'variant_code' => 'X01',
                'version' => '00',
                'title' => 'PINTURA BLANCO CLARA 020-01',
                'brand' => 'COMEX',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS EXTERIOR BASE',
                'style' => $style,
                'pre_code' => 'MEB01',
                'variant_code' => 'X02',
                'version' => '00',
                'title' => 'PLASTER CONCRETO APARENTE',
                'brand' => 'KIMIKOLOR',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS EXTERIOR BASE',
                'style' => $style,
                'pre_code' => 'MEB01',
                'variant_code' => 'X03',
                'version' => '00',
                'title' => 'PLASTER BLANCO SASCAB',
                'brand' => 'KIMIKOLOR',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS EXTERIOR BASE',
                'style' => $style,
                'pre_code' => 'MEB01',
                'variant_code' => 'X04',
                'version' => '00',
                'title' => 'PLASTER ROSA',
                'brand' => 'KIMIKOLOR',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS EXTERIOR BASE',
                'style' => $style,
                'pre_code' => 'MEB01',
                'variant_code' => 'X05',
                'version' => '00',
                'title' => 'PLASTER AZUL',
                'brand' => 'KIMIKOLOR',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS EXTERIOR BASE',
                'style' => $style,
                'pre_code' => 'MEB01',
                'variant_code' => 'X06',
                'version' => '00',
                'title' => 'PLASTER NARANJA TICUL',
                'brand' => 'KIMIKOLOR',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS EXTERIOR BASE',
                'style' => $style,
                'pre_code' => 'MEB01',
                'variant_code' => 'X07',
                'version' => '00',
                'title' => 'PLASTER ROJO',
                'brand' => 'KIMIKOLOR',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS EXTERIOR BASE',
                'style' => $style,
                'pre_code' => 'MEB01',
                'variant_code' => 'X08',
                'version' => '00',
                'title' => 'PINTURA GRIS ESPÁTULA 312-02',
                'brand' => 'COMEX',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS EXTERIOR BASE',
                'style' => $style,
                'pre_code' => 'MEB01',
                'variant_code' => 'X09',
                'version' => '00',
                'title' => 'PINTURA NEUTRO MUSEO 276-01',
                'brand' => 'COMEX',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS EXTERIOR BASE',
                'style' => $style,
                'pre_code' => 'MEB01',
                'variant_code' => 'X10',
                'version' => '00',
                'title' => 'PINTURA ROJO AJIJIC 083-03',
                'brand' => 'COMEX',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS EXTERIOR BASE',
                'style' => $style,
                'pre_code' => 'MEB01',
                'variant_code' => 'X11',
                'version' => '00',
                'title' => 'PINTURA AZUL SURF 176-03',
                'brand' => 'COMEX',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS EXTERIOR BASE',
                'style' => $style,
                'pre_code' => 'MEB01',
                'variant_code' => 'X12',
                'version' => '00',
                'title' => 'PINTURA NARANJA INCIENSO H3-09',
                'brand' => 'COMEX',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS EXTERIOR BASE',
                'style' => $style,
                'pre_code' => 'MEB01',
                'variant_code' => 'X13',
                'version' => '00',
                'title' => 'PINTURA MORADO ANTICA A4-08',
                'brand' => 'COMEX',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS EXTERIOR BASE',
                'style' => $style,
                'pre_code' => 'MEB01',
                'variant_code' => 'X14',
                'version' => '00',
                'title' => 'PINTURA ROJO AMAPOLA D2-14',
                'brand' => 'COMEX',
                'base_price' => 0,
                'image_url' => '',
            ],

            // MUROS EXTERIOR ACENTO 01
            [
                'category_name' => 'MUROS EXTERIOR ACENTO 01',
                'style' => $style,
                'pre_code' => 'MEA01',
                'variant_code' => 'X01',
                'version' => '00',
                'title' => 'PINTURA BLANCO CLARA 020-01',
                'brand' => 'COMEX',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS EXTERIOR ACENTO 01',
                'style' => $style,
                'pre_code' => 'MEA01',
                'variant_code' => 'X02',
                'version' => '00',
                'title' => 'PLASTER CONCRETO APARENTE',
                'brand' => 'KIMIKOLOR',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS EXTERIOR ACENTO 01',
                'style' => $style,
                'pre_code' => 'MEA01',
                'variant_code' => 'X03',
                'version' => '00',
                'title' => 'PLASTER BLANCO SASCAB',
                'brand' => 'KIMIKOLOR',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS EXTERIOR ACENTO 01',
                'style' => $style,
                'pre_code' => 'MEA01',
                'variant_code' => 'X04',
                'version' => '00',
                'title' => 'PLASTER ROSA',
                'brand' => 'KIMIKOLOR',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS EXTERIOR ACENTO 01',
                'style' => $style,
                'pre_code' => 'MEA01',
                'variant_code' => 'X05',
                'version' => '00',
                'title' => 'PLASTER AZUL',
                'brand' => 'KIMIKOLOR',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS EXTERIOR ACENTO 01',
                'style' => $style,
                'pre_code' => 'MEA01',
                'variant_code' => 'X06',
                'version' => '00',
                'title' => 'PLASTER NARANJA TICUL',
                'brand' => 'KIMIKOLOR',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS EXTERIOR ACENTO 01',
                'style' => $style,
                'pre_code' => 'MEA01',
                'variant_code' => 'X07',
                'version' => '00',
                'title' => 'PLASTER ROJO CONKAL',
                'brand' => 'KIMIKOLOR',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS EXTERIOR ACENTO 01',
                'style' => $style,
                'pre_code' => 'MEA01',
                'variant_code' => 'X08',
                'version' => '00',
                'title' => 'PINTURA GRIS ESPÁTULA 312-02',
                'brand' => 'COMEX',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS EXTERIOR ACENTO 01',
                'style' => $style,
                'pre_code' => 'MEA01',
                'variant_code' => 'X09',
                'version' => '00',
                'title' => 'PINTURA NEUTRO MUSEO 276-01',
                'brand' => 'COMEX',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS EXTERIOR ACENTO 01',
                'style' => $style,
                'pre_code' => 'MEA01',
                'variant_code' => 'X10',
                'version' => '00',
                'title' => 'PINTURA ROJO AJIJIC 083-03',
                'brand' => 'COMEX',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS EXTERIOR ACENTO 01',
                'style' => $style,
                'pre_code' => 'MEA01',
                'variant_code' => 'X11',
                'version' => '00',
                'title' => 'PINTURA AZUL SURF 176-03',
                'brand' => 'COMEX',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS EXTERIOR ACENTO 01',
                'style' => $style,
                'pre_code' => 'MEA01',
                'variant_code' => 'X12',
                'version' => '00',
                'title' => 'PINTURA NARANJA INCIENSO H3-09',
                'brand' => 'COMEX',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS EXTERIOR ACENTO 01',
                'style' => $style,
                'pre_code' => 'MEA01',
                'variant_code' => 'X13',
                'version' => '00',
                'title' => 'PINTURA MORADO ANTICA A4-08',
                'brand' => 'COMEX',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'MUROS EXTERIOR ACENTO 01',
                'style' => $style,
                'pre_code' => 'MEA01',
                'variant_code' => 'X14',
                'version' => '00',
                'title' => 'PINTURA ROJO AMAPOLA D2-14',
                'brand' => 'COMEX',
                'base_price' => 0,
                'image_url' => '',
            ],

            // PLAFONES
            [
                'category_name' => 'PLAFONES',
                'style' => $style,
                'pre_code' => 'PLA01',
                'variant_code' => 'X01',
                'version' => '00',
                'title' => 'PINTURA BLANCO CLARA 020-01',
                'brand' => 'COMEX',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'PLAFONES',
                'style' => $style,
                'pre_code' => 'PLA01',
                'variant_code' => 'X02',
                'version' => '00',
                'title' => 'PLASTER CONCRETO APARENTE',
                'brand' => 'KIMIKOLOR',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'PLAFONES',
                'style' => $style,
                'pre_code' => 'PLA01',
                'variant_code' => 'X03',
                'version' => '00',
                'title' => 'PLASTER BLANCO SASCAB',
                'brand' => 'KIMIKOLOR',
                'base_price' => 0,
                'image_url' => '',
            ],

            // PUERTAS
            [
                'category_name' => 'PUERTAS',
                'style' => $style,
                'pre_code' => 'PUE01',
                'variant_code' => 'X01',
                'version' => '00',
                'title' => 'TAMBOR DE TRIPLAY DE CAOBILLA NATURAL',
                'brand' => 'BETA STUDIO',
                'base_price' => 7300.00,
                'image_url' => '',
            ],
            [
                'category_name' => 'PUERTAS',
                'style' => $style,
                'pre_code' => 'PUE01',
                'variant_code' => 'X02',
                'version' => '00',
                'title' => 'TAMBOR DE TRIPLAY DE ENCINO ENTINTADO NOGAL',
                'brand' => 'BETA STUDIO',
                'base_price' => 7700.00,
                'image_url' => '',
            ],
            [
                'category_name' => 'PUERTAS',
                'style' => $style,
                'pre_code' => 'PUE01',
                'variant_code' => 'X03',
                'version' => '00',
                'title' => 'TAMBOR DE TRIPLAY DE ENCINO ENTINTADO CEDRO',
                'brand' => 'BETA STUDIO',
                'base_price' => 7700.00,
                'image_url' => '',
            ],

            // CANCELERÍA
            [
                'category_name' => 'CANCELERÍA',
                'style' => $style,
                'pre_code' => 'CAN01',
                'variant_code' => 'X01',
                'version' => '00',
                'title' => 'PERFIL DE ALUMINIO SERIE 70 DE EUROVENT COLOR NEGRO',
                'brand' => '',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'CANCELERÍA',
                'style' => $style,
                'pre_code' => 'CAN01',
                'variant_code' => 'X02',
                'version' => '00',
                'title' => 'PERFIL DE ALUMINIO SERIE 70 DE EUROVENT COLOR CHAMPAGNE',
                'brand' => '',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'CANCELERÍA',
                'style' => $style,
                'pre_code' => 'CAN01',
                'variant_code' => 'X03',
                'version' => '00',
                'title' => 'PERFIL DE ALUMINIO SERIE 70 DE EUROVENT COLOR MADERA',
                'brand' => '',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'CANCELERÍA',
                'style' => $style,
                'pre_code' => 'CAN01',
                'variant_code' => 'X04',
                'version' => '00',
                'title' => 'PERFIL DE ALUMINIO SERIE 70 DE EUROVENT COLOR BLANCO',
                'brand' => '',
                'base_price' => 0,
                'image_url' => '',
            ],

            // CARPINTERÍA
            [
                'category_name' => 'COCINAS, CLOSET Y MUEBLES BAJO CUBIERTA',
                'style' => $style,
                'pre_code' => 'CAR01',
                'variant_code' => 'X01',
                'version' => '00',
                'title' => 'TABLERO DE MDF O MDP LAMINADO TIPO ROBLE',
                'brand' => '',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'COCINAS, CLOSET Y MUEBLES BAJO CUBIERTA',
                'style' => $style,
                'pre_code' => 'CAR01',
                'variant_code' => 'X02',
                'version' => '00',
                'title' => 'TABLERO DE MDF O MDP LAMINADO TIPO BEIGE MATE LISO',
                'brand' => '',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'COCINAS, CLOSET Y MUEBLES BAJO CUBIERTA',
                'style' => $style,
                'pre_code' => 'CAR01',
                'variant_code' => 'X03',
                'version' => '00',
                'title' => 'TABLERO DE MDF O MDP LAMINADO TIPO CEDRO',
                'brand' => '',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'COCINAS, CLOSET Y MUEBLES BAJO CUBIERTA',
                'style' => $style,
                'pre_code' => 'CAR01',
                'variant_code' => 'X04',
                'version' => '00',
                'title' => 'TABLERO DE MDF O MDP LAMINADO TIPO BLANCO MATE LISO',
                'brand' => '',
                'base_price' => 0,
                'image_url' => '',
            ],

            // BAÑOS
            [
                'category_name' => 'GRIFERÍA Y ACCESORIOS DE BAÑO',
                'style' => $style,
                'pre_code' => 'BAN01',
                'variant_code' => 'X01',
                'version' => '00',
                'title' => 'GRIFERÍA Y ACCESORIOS ACABADO CROMO',
                'brand' => '',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'GRIFERÍA Y ACCESORIOS DE BAÑO',
                'style' => $style,
                'pre_code' => 'BAN01',
                'variant_code' => 'X02',
                'version' => '00',
                'title' => 'GRIFERÍA Y ACCESORIOS ACABADO DORADO',
                'brand' => '',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'GRIFERÍA Y ACCESORIOS DE BAÑO',
                'style' => $style,
                'pre_code' => 'BAN01',
                'variant_code' => 'X03',
                'version' => '00',
                'title' => 'GRIFERÍA Y ACCESORIOS ACABADO NEGRO MATE',
                'brand' => '',
                'base_price' => 0,
                'image_url' => '',
            ],

            // ACCESORIOS ELÉCTRICOS
            [
                'category_name' => 'ACCESORIOS ELÉCTRICOS',
                'style' => $style,
                'pre_code' => 'AEL01',
                'variant_code' => 'X01',
                'version' => '00',
                'title' => 'ACCESORIOS ELÉCTRICOS Y LUMINARIAS ACABADO SATINADO',
                'brand' => '',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'ACCESORIOS ELÉCTRICOS',
                'style' => $style,
                'pre_code' => 'AEL01',
                'variant_code' => 'X02',
                'version' => '00',
                'title' => 'ACCESORIOS ELÉCTRICOS Y LUMINARIAS ACABADO BLANCO',
                'brand' => '',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'ACCESORIOS ELÉCTRICOS',
                'style' => $style,
                'pre_code' => 'AEL01',
                'variant_code' => 'X03',
                'version' => '00',
                'title' => 'ACCESORIOS ELÉCTRICOS Y LUMINARIAS ACABADO NEGRO MATE',
                'brand' => '',
                'base_price' => 0,
                'image_url' => '',
            ],

            // ACCESORIOS PUERTAS
            [
                'category_name' => 'ACCESORIOS PUERTAS',
                'style' => $style,
                'pre_code' => 'APU01',
                'variant_code' => 'X01',
                'version' => '00',
                'title' => 'ACCESORIOS DE PUERTAS ACABADO ALUMINIO SATINADO',
                'brand' => '',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'ACCESORIOS PUERTAS',
                'style' => $style,
                'pre_code' => 'APU01',
                'variant_code' => 'X02',
                'version' => '00',
                'title' => 'ACCESORIOS DE PUERTAS ACABADO DORADO',
                'brand' => '',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'ACCESORIOS PUERTAS',
                'style' => $style,
                'pre_code' => 'APU01',
                'variant_code' => 'X03',
                'version' => '00',
                'title' => 'ACCESORIOS DE PUERTAS ACABADO NEGRO MATE',
                'brand' => '',
                'base_price' => 0,
                'image_url' => '',
            ],

            // ACCESORIOS CLOSETS
            [
                'category_name' => 'ACCESORIOS CLOSETS',
                'style' => $style,
                'pre_code' => 'ACL01',
                'variant_code' => 'X01',
                'version' => '00',
                'title' => 'ACCESORIOS DE PUERTAS ACABADO ALUMINIO SATINADO',
                'brand' => '',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'ACCESORIOS CLOSETS',
                'style' => $style,
                'pre_code' => 'ACL01',
                'variant_code' => 'X02',
                'version' => '00',
                'title' => 'ACCESORIOS DE PUERTAS ACABADO DORADO',
                'brand' => '',
                'base_price' => 0,
                'image_url' => '',
            ],
            [
                'category_name' => 'ACCESORIOS CLOSETS',
                'style' => $style,
                'pre_code' => 'ACL01',
                'variant_code' => 'X03',
                'version' => '00',
                'title' => 'ACCESORIOS DE PUERTAS ACABADO NEGRO MATE',
                'brand' => '',
                'base_price' => 0,
                'image_url' => '',
            ],
        ];

        foreach ($products as $product) {
            $categoryId = DB::table('categories')
                ->where('name', $product['category_name'])
                ->where('style', $style)
                ->value('id');

            if ($categoryId) {
                DB::table('products')->insert([
                    'category_id' => $categoryId,
                    'style' => $style,
                    'pre_code' => $product['pre_code'],
                    'variant_code' => $product['variant_code'],
                    'version' => $product['version'],
                    'title' => $product['title'],
                    'brand' => $product['brand'],
                    'base_price' => $product['base_price'],
                    'image_url' => $product['image_url'],
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }
        }
    }
}
