<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeederTulum extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'category_name' => 'PISOS INTERIORES',
                'pre_code' => 'PIN01',
                'variant_code' => 'T01',
                'version' => '00',
                'description' => 'TRAVERTINO PUEBLA FIORITO PULIDO MATE. FORMATO 30 cm x LARGOS LIBRES',
                'brand' => 'MIDO',
                'base_price' => 418.00
            ],
            [
                'category_name' => 'PISOS INTERIORES',
                'pre_code' => 'PIN01',
                'variant_code' => 'T02',
                'version' => '00',
                'description' => 'MARMOL SANTO TOMÁS PULIDO MATE. FORMATO 30 cm x LARGOS LIBRES',
                'brand' => 'MIDO',
                'base_price' => 530.00
            ],
            [
                'category_name' => 'PISOS INTERIORES',
                'pre_code' => 'PIN01',
                'variant_code' => 'T03',
                'version' => '00',
                'description' => 'CERÁMICO TIPO MADERA. MOD. RAINFOREST COLOR TAUPE. FORMATO 20X60',
                'brand' => 'INTERCERAMIC',
                'base_price' => 269.00
            ],
            [
                'category_name' => 'PISOS INTERIORES',
                'pre_code' => 'PIN01',
                'variant_code' => 'T04',
                'version' => '00',
                'description' => 'CERÁMICO TIPO MADERA. MOD. RAINFOREST COLOR NOGAL. FORMATO 20X60',
                'brand' => 'INTERCERAMIC',
                'base_price' => 269.00
            ],
            [
                'category_name' => 'PISOS INTERIORES',
                'pre_code' => 'PIN01',
                'variant_code' => 'T05',
                'version' => '00',
                'description' => 'CERÁMICO TIPO CEMENTO MODELO CREATO COLOR TAUPE. FORMATO 60X120',
                'brand' => 'INTERCERAMIC',
                'base_price' => 359.00
            ],
            [
                'category_name' => 'PISOS INTERIORES',
                'pre_code' => 'PIN01',
                'variant_code' => 'T06',
                'version' => '00',
                'description' => 'CERÁMICO TIPO PIEDRA MODELO ACADIA COLOR TREMONT BROWN. FORMATO 60X60',
                'brand' => 'INTERCERAMIC',
                'base_price' => 299.00
            ],
            [
                'category_name' => 'PISOS REGADERAS',
                'pre_code' => 'PRE01',
                'variant_code' => 'T01',
                'version' => '00',
                'description' => 'TRAVERTINO PUEBLA FIORITO AVEJENTADO. FORMATO 30 cm x LARGOS LIBRES',
                'brand' => 'MIDO',
                'base_price' => 439.00
            ],
            [
                'category_name' => 'PISOS REGADERAS',
                'pre_code' => 'PRE01',
                'variant_code' => 'T02',
                'version' => '00',
                'description' => 'MÁRMOL SANTO TOMÁS PULIDO AVEJENTADO. FORMATO 30 cm x LARGOS LIBRES',
                'brand' => 'MIDO',
                'base_price' => 544.00
            ],
            [
                'category_name' => 'PISOS REGADERAS',
                'pre_code' => 'PRE01',
                'variant_code' => 'T03',
                'version' => '00',
                'description' => 'CERÁMICO TIPO PIEDRA MOD. MATERIA COLOR TAUPE. FORMATO 60X60',
                'brand' => 'INTERCERAMIC',
                'base_price' => 289.00
            ],
            [
                'category_name' => 'PISOS REGADERAS',
                'pre_code' => 'PRE01',
                'variant_code' => 'T04',
                'version' => '00',
                'description' => 'CERÁMICO TIPO PIEDRA MOD. MATERIA COLOR MARRONE. FORMATO 60X60',
                'brand' => 'INTERCERAMIC',
                'base_price' => 289.00
            ],
            [
                'category_name' => 'MESETA COCINA',
                'pre_code' => 'MES01',
                'variant_code' => 'T01',
                'version' => '00',
                'description' => 'GRANITO ITAUNAS PULIDO',
                'brand' => 'MIDO',
                'base_price' => 80,
            ],
            [
                'category_name' => 'MESETA COCINA',
                'pre_code' => 'MES01',
                'variant_code' => 'T02',
                'version' => '00',
                'description' => 'GRANITO SAN GABRIEL LEATHER',
                'brand' => 'MIDO',
                'base_price' => 95,
            ],
            [
                'category_name' => 'MESETA COCINA',
                'pre_code' => 'MES01',
                'variant_code' => 'T03',
                'version' => '00',
                'description' => 'GRANITO SANTA CECILIA',
                'brand' => 'MIDO',
                'base_price' => 65,
            ],
            [
                'category_name' => 'MESETAS BAÑOS',
                'pre_code' => 'MES02',
                'variant_code' => 'T01',
                'version' => '00',
                'description' => 'GRANITO ITAUNAS PULIDO',
                'brand' => 'MIDO',
                'base_price' => 80,
            ],
            [
                'category_name' => 'MESETAS BAÑOS',
                'pre_code' => 'MES02',
                'variant_code' => 'T02',
                'version' => '00',
                'description' => 'GRANITO SAN GABRIEL LEATHER',
                'brand' => 'MIDO',
                'base_price' => 95,
            ],
            [
                'category_name' => 'MESETAS BAÑOS',
                'pre_code' => 'MES02',
                'variant_code' => 'T03',
                'version' => '00',
                'description' => 'GRANITO SANTA CECILIA',
                'brand' => 'MIDO',
                'base_price' => 65,
            ],
            [
                'category_name' => 'MUROS REGADERAS',
                'pre_code' => 'MRE01',
                'variant_code' => 'T01',
                'version' => '00',
                'description' => 'TRAVERTINO PUEBLA FIORITO AVEJENTADO. FORMATO 30 cm x LARGOS LIBRES',
                'brand' => 'MIDO',
                'base_price' => 439,
            ],
            [
                'category_name' => 'MUROS REGADERAS',
                'pre_code' => 'MRE01',
                'variant_code' => 'T02',
                'version' => '00',
                'description' => 'MARMOL SANTO TOMÁS PULIDO AVEJENTADO. FORMATO 30 cm x LARGOS LIBRES',
                'brand' => 'MIDO',
                'base_price' => 544,
            ],
            [
                'category_name' => 'MUROS REGADERAS',
                'pre_code' => 'MRE01',
                'variant_code' => 'T03',
                'version' => '00',
                'description' => 'CERÁMICO TIPO PIEDRA MOD. MATERIA COLOR TAUPE. FORMATO 60X60',
                'brand' => 'INTERCERAMIC',
                'base_price' => 289,
            ],
            [
                'category_name' => 'MUROS REGADERAS',
                'pre_code' => 'MRE01',
                'variant_code' => 'T04',
                'version' => '00',
                'description' => 'CERÁMICO TIPO PIEDRA MOD. MATERIA COLOR MARRONE. FORMATO 60X60',
                'brand' => 'INTERCERAMIC',
                'base_price' => 289,
            ],
            [
                'category_name' => 'MUROS INTERIORES BASE',
                'pre_code' => 'MIB01',
                'variant_code' => 'T01',
                'version' => '00',
                'description' => 'PINTURA BLANCO CLARA 020-01',
                'brand' => 'COMEX',
                'base_price' => 0,
            ],
            [
                'category_name' => 'MUROS INTERIORES BASE',
                'pre_code' => 'MIB01',
                'variant_code' => 'T02',
                'version' => '00',
                'description' => 'PLASTER CHUKUM',
                'brand' => 'KIMIKOLOR',
                'base_price' => 0,
            ],
            [
                'category_name' => 'MUROS INTERIORES BASE',
                'pre_code' => 'MIB01',
                'variant_code' => 'T03',
                'version' => '00',
                'description' => 'PLASTER NARANJA TICUL',
                'brand' => 'KIMIKOLOR',
                'base_price' => 0,
            ],
            [
                'category_name' => 'MUROS INTERIORES BASE',
                'pre_code' => 'MIB01',
                'variant_code' => 'T04',
                'version' => '00',
                'description' => 'PLASTER CAFÉ MOTUL',
                'brand' => 'KIMIKOLOR',
                'base_price' => 0,
            ],
            [
                'category_name' => 'MUROS INTERIORES BASE',
                'pre_code' => 'MIB01',
                'variant_code' => 'T05',
                'version' => '00',
                'description' => 'PINTURA AMARILLO TURRÓN I4-05',
                'brand' => 'COMEX',
                'base_price' => 0,
            ],
            [
                'category_name' => 'MUROS INTERIORES BASE',
                'pre_code' => 'MIB01',
                'variant_code' => 'T06',
                'version' => '00',
                'description' => 'PINTURA COLOR NEUTRO YUCA 269-04',
                'brand' => 'COMEX',
                'base_price' => 0,
            ],
            [
                'category_name' => 'MUROS INTERIORES BASE',
                'pre_code' => 'MIB01',
                'variant_code' => 'T07',
                'version' => '00',
                'description' => 'PINTURA NARANJA INCIENSO H3-09',
                'brand' => 'COMEX',
                'base_price' => 0,
            ],
            [
                'category_name' => 'MUROS INTERIORES ACENTO',
                'pre_code' => 'MIA01',
                'variant_code' => 'T01',
                'version' => '00',
                'description' => 'PINTURA BLANCO CLARA 020-01',
                'brand' => 'COMEX',
                'base_price' => 0,
            ],
            [
                'category_name' => 'MUROS INTERIORES ACENTO',
                'pre_code' => 'MIA01',
                'variant_code' => 'T02',
                'version' => '00',
                'description' => 'PLASTER CHUKUM',
                'brand' => 'KIMIKOLOR',
                'base_price' => 0,
            ],
            [
                'category_name' => 'MUROS INTERIORES ACENTO',
                'pre_code' => 'MIA01',
                'variant_code' => 'T03',
                'version' => '00',
                'description' => 'PLASTER NARANJA TICUL',
                'brand' => 'KIMIKOLOR',
                'base_price' => 0,
            ],
            [
                'category_name' => 'MUROS INTERIORES ACENTO',
                'pre_code' => 'MIA01',
                'variant_code' => 'T04',
                'version' => '00',
                'description' => 'PLASTER CAFÉ MOTUL',
                'brand' => 'KIMIKOLOR',
                'base_price' => 0,
            ],
            [
                'category_name' => 'MUROS INTERIORES ACENTO',
                'pre_code' => 'MIA01',
                'variant_code' => 'T05',
                'version' => '00',
                'description' => 'PINTURA AMARILLO TURRÓN I4-05',
                'brand' => 'COMEX',
                'base_price' => 0,
            ],
            [
                'category_name' => 'MUROS INTERIORES ACENTO',
                'pre_code' => 'MIA01',
                'variant_code' => 'T06',
                'version' => '00',
                'description' => 'PINTURA COLOR NEUTRO YUCA 269-04',
                'brand' => 'COMEX',
                'base_price' => 0,
            ],
            [
                'category_name' => 'MUROS INTERIORES ACENTO',
                'pre_code' => 'MIA01',
                'variant_code' => 'T07',
                'version' => '00',
                'description' => 'PINTURA NARANJA INCIENSO H3-09',
                'brand' => 'COMEX',
                'base_price' => 0,
            ],
            [
                'category_name' => 'MUROS EXTERIORES BASE',
                'pre_code' => 'MEB01',
                'variant_code' => 'T01',
                'version' => '00',
                'description' => 'PLASTER CHUKUM',
                'brand' => 'KIMIKOLOR',
                'base_price' => 0,
            ],
            [
                'category_name' => 'MUROS EXTERIORES BASE',
                'pre_code' => 'MEB01',
                'variant_code' => 'T02',
                'version' => '00',
                'description' => 'PLASTER CAFÉ MOTUL',
                'brand' => 'KIMIKOLOR',
                'base_price' => 0,
            ],
            [
                'category_name' => 'MUROS EXTERIORES BASE',
                'pre_code' => 'MEB01',
                'variant_code' => 'T03',
                'version' => '00',
                'description' => 'PLASTER NARANJA TICUL',
                'brand' => 'KIMIKOLOR',
                'base_price' => 0,
            ],
            [
                'category_name' => 'MUROS EXTERIORES BASE',
                'pre_code' => 'MEB01',
                'variant_code' => 'T04',
                'version' => '00',
                'description' => 'PINTURA AMARILLO TURRÓN I4-05',
                'brand' => 'COMEX',
                'base_price' => 0,
            ],
            [
                'category_name' => 'MUROS EXTERIORES BASE',
                'pre_code' => 'MEB01',
                'variant_code' => 'T05',
                'version' => '00',
                'description' => 'PINTURA COLOR NEUTRO YUCA 269-04',
                'brand' => 'COMEX',
                'base_price' => 0,
            ],
            [
                'category_name' => 'MUROS EXTERIORES BASE',
                'pre_code' => 'MEB01',
                'variant_code' => 'T06',
                'version' => '00',
                'description' => 'PINTURA NARANJA INCIENSO H3-09',
                'brand' => 'COMEX',
                'base_price' => 0,
            ],
            [
                'category_name' => 'MUROS EXTERIORES ACENTO 01',
                'pre_code' => 'MEA01',
                'variant_code' => 'T01',
                'version' => '00',
                'description' => 'LAMBRÍN MADERA ARKOWOOD EP22 TEKA',
                'brand' => 'ARKOS',
                'base_price' => 950.00,
            ],
            [
                'category_name' => 'MUROS EXTERIORES ACENTO 01',
                'pre_code' => 'MEA01',
                'variant_code' => 'T02',
                'version' => '00',
                'description' => 'CHAPA LAJA CREMA MAYA IRREGULAR',
                'brand' => '',
                'base_price' => 0,
            ],
            [
                'category_name' => 'MUROS EXTERIORES ACENTO 01',
                'pre_code' => 'MEA01',
                'variant_code' => 'T03',
                'version' => '00',
                'description' => 'PLASTER CHUKUM',
                'brand' => 'KIMIKOLOR',
                'base_price' => 290,
            ],
            [
                'category_name' => 'MUROS EXTERIORES ACENTO 01',
                'pre_code' => 'MEA01',
                'variant_code' => 'T04',
                'version' => '00',
                'description' => 'PLASTER CAFÉ MOTUL',
                'brand' => 'KIMIKOLOR',
                'base_price' => 290,
            ],
            [
                'category_name' => 'MUROS EXTERIORES ACENTO 01',
                'pre_code' => 'MEA01',
                'variant_code' => 'T05',
                'version' => '00',
                'description' => 'PLASTER NARANJA TICUL',
                'brand' => 'KIMIKOLOR',
                'base_price' => 290,
            ],
            [
                'category_name' => 'MUROS EXTERIORES ACENTO 01',
                'pre_code' => 'MEA01',
                'variant_code' => 'T06',
                'version' => '00',
                'description' => 'PINTURA AMARILLO TURRÓN I4-05',
                'brand' => 'COMEX',
                'base_price' => 0,
            ],
            [
                'category_name' => 'MUROS EXTERIORES ACENTO 01',
                'pre_code' => 'MEA01',
                'variant_code' => 'T07',
                'version' => '00',
                'description' => 'PINTURA COLOR NEUTRO YUCA 269-04',
                'brand' => 'COMEX',
                'base_price' => 0,
            ],
            [
                'category_name' => 'MUROS EXTERIORES ACENTO 01',
                'pre_code' => 'MEA01',
                'variant_code' => 'T08',
                'version' => '00',
                'description' => 'PINTURA NARANJA INCIENSO H3-09',
                'brand' => 'COMEX',
                'base_price' => 0,
            ],
            [
                'category_name' => 'MUROS EXTERIORES ACENTO 02',
                'pre_code' => 'MEA02',
                'variant_code' => 'T01',
                'version' => '00',
                'description' => 'LAMBRÍN MADERA ARKOWOOD EP22 TEKA',
                'brand' => 'ARKOS',
                'base_price' => 950.00,
            ],
            [
                'category_name' => 'MUROS EXTERIORES ACENTO 02',
                'pre_code' => 'MEA02',
                'variant_code' => 'T02',
                'version' => '00',
                'description' => 'CHAPA LAJA CREMA MAYA IRREGULAR',
                'brand' => '',
                'base_price' => 0,
            ],
            [
                'category_name' => 'MUROS EXTERIORES ACENTO 02',
                'pre_code' => 'MEA02',
                'variant_code' => 'T03',
                'version' => '00',
                'description' => 'PLASTER CHUKUM',
                'brand' => 'KIMIKOLOR',
                'base_price' => 290,
            ],
            [
                'category_name' => 'MUROS EXTERIORES ACENTO 02',
                'pre_code' => 'MEA02',
                'variant_code' => 'T04',
                'version' => '00',
                'description' => 'PLASTER CAFÉ MOTUL',
                'brand' => 'KIMIKOLOR',
                'base_price' => 290,
            ],
            [
                'category_name' => 'MUROS EXTERIORES ACENTO 02',
                'pre_code' => 'MEA02',
                'variant_code' => 'T05',
                'version' => '00',
                'description' => 'PLASTER NARANJA TICUL',
                'brand' => 'KIMIKOLOR',
                'base_price' => 290,
            ],
            [
                'category_name' => 'MUROS EXTERIORES ACENTO 02',
                'pre_code' => 'MEA02',
                'variant_code' => 'T06',
                'version' => '00',
                'description' => 'PINTURA AMARILLO TURRÓN I4-05',
                'brand' => 'COMEX',
                'base_price' => 0,
            ],
            [
                'category_name' => 'MUROS EXTERIORES ACENTO 02',
                'pre_code' => 'MEA02',
                'variant_code' => 'T07',
                'version' => '00',
                'description' => 'PINTURA COLOR NEUTRO YUCA 269-04',
                'brand' => 'COMEX',
                'base_price' => 0,
            ],
            [
                'category_name' => 'MUROS EXTERIORES ACENTO 02',
                'pre_code' => 'MEA02',
                'variant_code' => 'T08',
                'version' => '00',
                'description' => 'PINTURA NARANJA INCIENSO H3-09',
                'brand' => 'COMEX',
                'base_price' => 0,
            ],
            [
                'category_name' => 'BASAMENTO',
                'pre_code' => 'BAS01',
                'variant_code' => 'T01',
                'version' => '00',
                'description' => 'CHAPA LAJA CREMA MAYA IRREGULAR',
                'brand' => '',
                'base_price' => 0,
            ],
            [
                'category_name' => 'BASAMENTO',
                'pre_code' => 'BAS01',
                'variant_code' => 'T02',
                'version' => '00',
                'description' => 'PLASTER CHUKUM',
                'brand' => 'KIMIKOLOR',
                'base_price' => 290,
            ],
            [
                'category_name' => 'BASAMENTO',
                'pre_code' => 'BAS01',
                'variant_code' => 'T03',
                'version' => '00',
                'description' => 'PLASTER CAFÉ MOTUL',
                'brand' => 'KIMIKOLOR',
                'base_price' => 290,
            ],
            [
                'category_name' => 'BASAMENTO',
                'pre_code' => 'BAS01',
                'variant_code' => 'T04',
                'version' => '00',
                'description' => 'PLASTER NARANJA TICUL',
                'brand' => 'KIMIKOLOR',
                'base_price' => 290,
            ],
            [
                'category_name' => 'BASAMENTO',
                'pre_code' => 'BAS01',
                'variant_code' => 'T05',
                'version' => '00',
                'description' => 'PINTURA AMARILLO TURRÓN I4-05',
                'brand' => 'COMEX',
                'base_price' => 0,
            ],
            [
                'category_name' => 'BASAMENTO',
                'pre_code' => 'BAS01',
                'variant_code' => 'T06',
                'version' => '00',
                'description' => 'PINTURA COLOR NEUTRO YUCA 269-04',
                'brand' => 'COMEX',
                'base_price' => 0,
            ],
            [
                'category_name' => 'BASAMENTO',
                'pre_code' => 'BAS01',
                'variant_code' => 'T07',
                'version' => '00',
                'description' => 'PINTURA NARANJA INCIENSO H3-09',
                'brand' => 'COMEX',
                'base_price' => 0,
            ],
                        
            [
                'category_name' => 'PLAFONES',
                'pre_code' => 'PLA01',
                'variant_code' => 'T01',
                'version' => '00',
                'description' => 'PINTURA BLANCO CLARA 020-01',
                'brand' => 'COMEX',
                'base_price' => 0,
            ],
            [
                'category_name' => 'PLAFONES',
                'pre_code' => 'PLA01',
                'variant_code' => 'T02',
                'version' => '00',
                'description' => 'PLASTER CHUKUM',
                'brand' => 'KIMIKOLOR',
                'base_price' => 290,
            ],
            [
                'category_name' => 'PLAFONES',
                'pre_code' => 'PLA01',
                'variant_code' => 'T03',
                'version' => '00',
                'description' => 'PLASTER CAFÉ MOTUL',
                'brand' => 'KIMIKOLOR',
                'base_price' => 290,
            ],
            [
                'category_name' => 'PUERTAS',
                'pre_code' => 'PUE01',
                'variant_code' => 'T01',
                'version' => '00',
                'description' => 'TAMBOR DE TRIPLAY DE CAOBILLA NATURAL',
                'brand' => 'BETA STUDIO',
                'base_price' => 7300.00,
            ],
            [
                'category_name' => 'PUERTAS',
                'pre_code' => 'PUE01',
                'variant_code' => 'T02',
                'version' => '00',
                'description' => 'TAMBOR DE TRIPLAY DE TZALAM NATURAL',
                'brand' => 'BETA STUDIO',
                'base_price' => 8000.00,
            ],
            [
                'category_name' => 'CANCELERÍA',
                'pre_code' => 'CAN01',
                'variant_code' => 'T01',
                'version' => '00',
                'description' => 'PERFIL DE ALUMINIO SERIE 70 DE EUROVENT COLOR NEGRO',
                'brand' => '',
                'base_price' => 0,
            ],
            [
                'category_name' => 'CANCELERÍA',
                'pre_code' => 'CAN01',
                'variant_code' => 'T02',
                'version' => '00',
                'description' => 'PERFIL DE ALUMINIO SERIE 70 DE EUROVENT COLOR CHAMPAGNE',
                'brand' => '',
                'base_price' => 0,
            ],
            [
                'category_name' => 'CANCELERÍA',
                'pre_code' => 'CAN01',
                'variant_code' => 'T03',
                'version' => '00',
                'description' => 'PERFIL DE ALUMINIO SERIE 70 DE EUROVENT COLOR MADERA',
                'brand' => '',
                'base_price' => 0,
            ],
            
            [
                'category_name' => 'CARPINTERÍA',
                'pre_code' => 'CAR01',
                'variant_code' => 'T01',
                'version' => '00',
                'description' => 'TABLERO DE MDF O MDP LAMINADO TIPO NOGAL',
                'brand' => '',
                'base_price' => 0,
            ],
            [
                'category_name' => 'CARPINTERÍA',
                'pre_code' => 'CAR01',
                'variant_code' => 'T02',
                'version' => '00',
                'description' => 'TABLERO DE MDF O MDP LAMINADO TIPO BEIGE MATE LISO',
                'brand' => '',
                'base_price' => 0,
            ],
            [
                'category_name' => 'CARPINTERÍA',
                'pre_code' => 'CAR01',
                'variant_code' => 'T03',
                'version' => '00',
                'description' => 'TABLERO DE MDF O MDP LAMINADO TIPO ROBLE',
                'brand' => '',
                'base_price' => 0,
            ],
            [
                'category_name' => 'CARPINTERÍA',
                'pre_code' => 'CAR01',
                'variant_code' => 'T04',
                'version' => '00',
                'description' => 'TABLERO DE MDF O MDP LAMINADO TIPO BLANCO MATE LISO',
                'brand' => '',
                'base_price' => 0,
            ],
            [
                'category_name' => 'BAÑOS',
                'pre_code' => 'BAN01',
                'variant_code' => 'T01',
                'version' => '00',
                'description' => 'GRIFERÍA Y ACCESORIOS ACABADO CROMO',
                'brand' => '',
                'base_price' => 0,
            ],
            [
                'category_name' => 'BAÑOS',
                'pre_code' => 'BAN01',
                'variant_code' => 'T02',
                'version' => '00',
                'description' => 'GRIFERÍA Y ACCESORIOS ACABADO DORADO',
                'brand' => '',
                'base_price' => 0,
            ],
            [
                'category_name' => 'BAÑOS',
                'pre_code' => 'BAN01',
                'variant_code' => 'T03',
                'version' => '00',
                'description' => 'GRIFERÍA Y ACCESORIOS ACABADO NEGRO MATE',
                'brand' => '',
                'base_price' => 0,
            ],
            [
                'category_name' => 'ACCESORIOS ELÉCTRICOS',
                'pre_code' => 'AEL01',
                'variant_code' => 'T01',
                'version' => '00',
                'description' => 'ACCESORIOS ELÉCTRICOS Y LUMINARIAS ACABADO SATINADO',
                'brand' => '',
                'base_price' => 0,
            ],
            [
                'category_name' => 'ACCESORIOS ELÉCTRICOS',
                'pre_code' => 'AEL01',
                'variant_code' => 'T02',
                'version' => '00',
                'description' => 'ACCESORIOS ELÉCTRICOS Y LUMINARIAS ACABADO BLANCO',
                'brand' => '',
                'base_price' => 0,
            ],
            [
                'category_name' => 'ACCESORIOS ELÉCTRICOS',
                'pre_code' => 'AEL01',
                'variant_code' => 'T03',
                'version' => '00',
                'description' => 'ACCESORIOS ELÉCTRICOS Y LUMINARIAS ACABADO NEGRO MATE',
                'brand' => '',
                'base_price' => 0,
            ],
            [
                'category_name' => 'ACCESORIOS PUERTAS',
                'pre_code' => 'APU01',
                'variant_code' => 'T01',
                'version' => '00',
                'description' => 'ACCESORIOS DE PUERTAS ACABADO ALUMINIO SATINADO',
                'brand' => '',
                'base_price' => 0,
            ],
            [
                'category_name' => 'ACCESORIOS PUERTAS',
                'pre_code' => 'APU01',
                'variant_code' => 'T02',
                'version' => '00',
                'description' => 'ACCESORIOS DE PUERTAS ACABADO DORADO',
                'brand' => '',
                'base_price' => 0,
            ],
            [
                'category_name' => 'ACCESORIOS PUERTAS',
                'pre_code' => 'APU01',
                'variant_code' => 'T03',
                'version' => '00',
                'description' => 'ACCESORIOS DE PUERTAS ACABADO NEGRO MATE',
                'brand' => '',
                'base_price' => 0,
            ],
            [
                'category_name' => 'ACCESORIOS CLOSETS',
                'pre_code' => 'ACL01',
                'variant_code' => 'T01',
                'version' => '00',
                'description' => 'ACCESORIOS DE PUERTAS ACABADO ALUMINIO SATINADO',
                'brand' => '',
                'base_price' => 0,
            ],
            [
                'category_name' => 'ACCESORIOS CLOSETS',
                'pre_code' => 'ACL01',
                'variant_code' => 'T02',
                'version' => '00',
                'description' => 'ACCESORIOS DE PUERTAS ACABADO DORADO',
                'brand' => '',
                'base_price' => 0,
            ],
            [
                'category_name' => 'ACCESORIOS CLOSETS',
                'pre_code' => 'ACL01',
                'variant_code' => 'T03',
                'version' => '00',
                'description' => 'ACCESORIOS DE PUERTAS ACABADO NEGRO MATE',
                'brand' => '',
                'base_price' => 0,
            ],
            
        ];

        foreach ($products as $product) {
            $categoryId = DB::table('categories')
            ->where('name', $product['category_name'])
            ->where('style', 'Tulum')
            ->value('id');

            if ($categoryId) {
                DB::table('products')->insert([
                    'category_id' => $categoryId,
                    'style' => 'Tulum',
                    'pre_code' => $product['pre_code'],
                    'variant_code' => $product['variant_code'],
                    'version' => $product['version'],
                    'description' => $product['description'],
                    'brand' => $product['brand'],
                    'base_price' => $product['base_price'],
                    'one_bedroom_price' => 0,
                    'two_bedroom_price' => 0,
                    'three_bedroom_price' => 0,
                    'four_bedroom_price' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }
        }
    }
}
